[package]
name = "decision_tables_service"
version = "0.1.0"
edition = "2021"

[lib]
name = "decision_tables_service"
crate-type = ["rlib", "cdylib"]

# Визначаємо виконуваний файл
[[bin]]
name = "decision_tables_service"
path = "src/main.rs"


[dependencies]
simd-json = "0.14"
calamine = { version = "0.22", features = ["dates"] }
chrono = "0.4"
paste = "1.0"
crossbeam = "0.8"
jni = "0.21"
